🇿🇦 Add departments and chapter 9 institutions
govdirectory/website pull request #188
Opened 2022-02-18 19:06 UTC by Ainali

Expanding on the South African state level organizations.

2022-02-19 10:36 UTC, Ainali commented
Turn this to draft since I found a new source for chapter nine organizations.

2022-02-19 20:08 UTC, Abbe98 requested changes

2022-02-19 20:08 UTC, Abbe98 commented on queries/generators/south-africa.rq
>    VALUES ?type {
This needs to be refected in countries.rq.

2022-02-21 15:01 UTC, Abbe98 approved these changes

2022-02-21 16:07 UTC, merged