hide-view-on-map
govdirectory/website pull request #240
Opened 2022-10-01 18:13 UTC by Farelion

2022-10-01 19:30 UTC, Abbe98 requested changes
We already have an utility class that can be used to hide it, let's use that one: https://github.com/govdirectory/website/blob/main/templates/layouts/layout.html#L41

2022-10-01 19:40 UTC, Farelion commented
Oh i didn`t see that we have class for this already, i`ve made changes

2022-10-02 13:10 UTC, Abbe98 approved these changes

2022-10-02 13:11 UTC, merged

2022-10-02 13:11 UTC, Abbe98 commented
Thank you @Farelion!