added static footer images
govdirectory/website pull request #241
Opened 2022-10-01 18:36 UTC by ankitdas09

Issue #234

2022-10-01 19:33 UTC, Abbe98 requested changes
Looks mostly good. Only a minor thing, lets use the SVG version for the "powered by Wikidata" badge as well to ensure we got source files checked in. The SVG version can be found here: https://upload.wikimedia.org/wikipedia/commons/4/41/Wikidata_Stamp_Rec_Light.svg

2022-10-02 05:47 UTC, ankitdas09 commented
@Abbe98 added the svg file for wikidata

2022-10-02 13:12 UTC, Abbe98 approved these changes

2022-10-02 13:12 UTC, Abbe98 commented
Thank you @ankitdas09 :rocket:

2022-10-02 13:13 UTC, merged