🦣 Add Mastodon to footer
govdirectory/website pull request #255
Opened 2022-11-06 19:55 UTC by Ainali

I added rel="me" to get the verified badge in Mastodon.

2022-11-07 08:44 UTC, Abbe98 requested changes

2022-11-07 08:44 UTC, Abbe98 commented on templates/layouts/layout.html
> +                    <li><a class="no-decoration" rel="me" href="https://wikis.world/@govdirectory">Mastodon</a></li>
I think we need to wrap the `rel="me"` into a if-statement to make sure it's only there on the start page because semantically org and country pages are about them not us.

2022-11-07 08:44 UTC, Abbe98 commented on templates/layouts/layout.html
> +                    <li><a class="no-decoration" rel="me" href="https://wikis.world/@govdirectory">Mastodon</a></li>
Maybe the `canonical` variable could be used to check if it's the page in question.

2022-11-07 21:49 UTC, Ainali commented on templates/layouts/layout.html
> +                    <li><a class="no-decoration" rel="me" href="https://wikis.world/@govdirectory">Mastodon</a></li>
Yes, I think that worked.

2023-03-31 13:22 UTC, Abbe98 approved these changes

2023-03-31 13:22 UTC, Abbe98 commented on templates/layouts/layout.html
> +                    <li><a class="no-decoration" {{- if eq "canonical" "" -}} rel="me" {{- end -}} href="https://wikis.world/@govdirectory">Mastodon</a></li>
This ended up being trickier than I expected. The current code checks if the string "canonical" matches the string "", the question becomes how we can access the contents of the `canonical` block and I'm not sure it can be done without changes to Snowman.

I will have a proper look the coming week as I have several open source sessions planed.

2023-03-31 13:23 UTC, Abbe98 commented
@Ainali updated but requires Snowman 0.4.

2023-03-31 14:30 UTC, merged