🧼🧽 Clean up CSS
govdirectory/website pull request #386
Opened 2024-05-22 17:56 UTC by RVA2869

- unnecessary code removed (details)
- standardize colors (all in lowercase hex)
- set a fixed width and height of the round buttons. (no CSS)
- timestamp section has been fixed<br>
before: 
```
.timestamp {
    text-align: right;
    margin-top: 0.5;
    margin-bottom: 0;
```

after: 
 ```
.timestamp {
    text-align: right;
    margin-top: .5em;
    margin-bottom: 0;
  }
```
The unit was missing from margin-top.

2024-05-24 13:17 UTC, Ainali commented
Thanks for starting on this maintenance task!

I like the unifying of cases and great with the explicit height and width of the buttons.

I am not sure about removing units when the value is zero, nor removing the zero when the value is between 0 and 1. Both those reduce legibility in my opinion.

I don't understand what you mean with "unnecessary code removed (details)", could you explain that further?

2024-05-24 13:26 UTC, Abbe98 commented
I like it and I think it makes it more consistent.

2024-05-24 13:27 UTC, Abbe98 requested changes

2024-05-24 13:27 UTC, Abbe98 commented on static/main.css
> +    background-color:#fff;
Lets add a space here as we are doing a cleanup.

2024-05-24 13:28 UTC, Abbe98 commented
Super minor note from my end, but that's it.

2024-05-25 12:46 UTC, RVA2869 commented
> I don't understand what you mean with "unnecessary code removed (details)", could you explain that further?

The unnecessary code is this:
>  I am not sure about removing units when the value is zero, nor removing the zero when the value is between 0 and 1.

Even with my limited knowledge of CSS, I can still read it.
The main user of the CSS is of course the browser (humans are a bonus)😉.

2024-05-25 13:32 UTC, Ainali approved these changes

2024-05-25 13:33 UTC, merged