Create PULL_REQUEST_TEMPLATE.md
govdirectory/website pull request #424
Opened 2024-10-09 10:53 UTC by eastermukora

Created a PR template to fit issue #401 and extended to cover basic scenarios in contribution.

Issue #401 - Create a Pull request template

## Type of Change
Documentation Update

##Checklist
- [ ] I have tested the changes locally, and they work as expected
- [ ] The code follows the project's coding standards and conventions
- [ ] No query or DB changes made.
- [ ] I have updated some of the relevant documentation in contributing.md
- [ ] I have mentioned the person responsible for reviewing this PR.

##Reviewers
@RVA2869

2024-10-09 12:17 UTC, Ainali commented on CONTRIBUTING.md
> +When submitting the pull request, please accompany it with a description of the problem you are trying to solve and the issue numbers that this pull request fixes.
The space at the end of this line should be removed.
```suggestion
When submitting the pull request, please accompany it with a description of the problem you are trying to solve and the issue numbers that this pull request fixes.
```

2024-10-09 12:19 UTC, Ainali commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Any **query or database changes** have been verified and are working correctly.
We don't have a local database (yet).
```suggestion
- [ ] Any **query changes** have been verified and are working correctly.
```

2024-10-09 12:21 UTC, Ainali commented
Thanks for working on this. In general, I think this is good, but there are a few things I think we should clean up before merging.

- The checkboxes in CONTRIBUTING are better as regular bullet points, as one will not really check anything there.
- I think we can skip the reviewer section and just use the GitHub functionality. Also, the contributor may not know who should review.

2024-10-09 15:04 UTC, eastermukora commented
That is right, I'd also like help reviewing contribution.md in such a way that it's more direct or concise.

2024-10-09 15:12 UTC, eastermukora reviewed
Edited the files for changes recommended

2024-10-09 16:51 UTC, Ainali approved these changes
This is good, thanks!

2024-10-09 16:54 UTC, Ainali requested changes

2024-10-09 16:54 UTC, Ainali commented on PULL_REQUEST_TEMPLATE.md
> +## Screenshots (applicable to UI changes)
Write this without an abbreviation so we don't need to update the jargon file. 
```suggestion
## Screenshots (applicable to user interface changes)
```

2024-10-09 16:55 UTC, Ainali commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] I have **mentioned** the person/team responsible for reviewing this PR.
This check box can go too, we don't need the contributor to know who should review.

2024-10-10 20:49 UTC, eastermukora reviewed
removed the 'mention code reviewer check box'

2024-10-11 06:06 UTC, Ainali approved these changes

2024-10-11 06:07 UTC, merged